[tool.coverage.run]
branch = true
source = [ "idp_v2_idp_agent" ]

[tool.coverage.report]
exclude_lines = [ "if TYPE_CHECKING:" ]
show_missing = true

[tool.pytest.ini_options]
addopts = """
 --cov
 --cov-report html:'../../../../coverage/packages/agents/idp-agent/idp_agent/html'
 --cov-report xml:'../../../../coverage/packages/agents/idp-agent/idp_agent/coverage.xml'
 --html='../../../../reports/packages/agents/idp-agent/idp_agent/unittests/html/index.html'
 --junitxml='../../../../reports/packages/agents/idp-agent/idp_agent/unittests/junit.xml'
"""

[tool.hatch.build.targets.wheel]
packages = [ "idp_v2_idp_agent" ]

[tool.hatch.metadata]
allow-direct-references = true

[tool.ruff]
exclude = [ ".ruff_cache", ".svn", ".tox", ".venv", "dist" ]
line-length = 120
indent-width = 4

  [tool.ruff.lint]
  select = [ "E", "F", "UP", "B", "SIM", "I" ]
  ignore = [ ]
  fixable = [ "ALL" ]
  unfixable = [ ]

[project]
name = "idp_v2.idp_agent"
version = "1.0.0"
description = "Automatically generated by Nx."
requires-python = ">=3.12"
readme = "README.md"
dependencies = [
  "aws-opentelemetry-distro==0.14.0",
  "bedrock-agentcore==0.1.7",
  "fastapi==0.123.0",
  "boto3==1.42.0",
  "mcp==1.22.0",
  "strands-agents==1.18.0",
  "strands-agents-tools==0.2.16",
  "uvicorn==0.38.0"
]

[build-system]
requires = [ "hatchling" ]
build-backend = "hatchling.build"

[dependency-groups]
dev = [ "fastapi[standard]==0.123.0" ]
